#!/usr/bin/expect -f
set timeout -1
set password "Sarik0770"

spawn scp -o StrictHostKeyChecking=no app.zip .env root@83.171.249.103:/root/
expect {
    "*assword:*" { send "$password\r"; exp_continue }
    eof
}

spawn ssh -o StrictHostKeyChecking=no root@83.171.249.103 "mkdir -p app && unzip -o app.zip -d app && mv .env app/.env && cd app && docker compose -f docker-compose.prod.yml up -d --build"
expect {
    "*assword:*" { send "$password\r"; exp_continue }
    eof
}
